export const country = [
  { value: "ar", label: "Argentina" },
  { value: "au", label: "Australia" },
  { value: "at", label: "Austria" },
  { value: "be", label: "Belgium" },
  { value: "zr", label: "Brazil" },
  { value: "bg", label: "Bulgaria" },
  { value: "ca", label: "Canada" },
  { value: "cn", label: "China" },
  { value: "co", label: "Colombia" },
  { value: "cu", label: "Cuba" },
  { value: "cz", label: "Czech Republic" },
  { value: "eg", label: "Egypt" },
  { value: "fr", label: "France" },
  { value: "de", label: "Germany" },
  { value: "gr", label: "Greece" },
  { value: "hk", label: "Hongkong" },
  { value: "hu", label: "Hungry" },
  { value: "in", label: "India" },
  { value: "id", label: "Indonesia" },
  { value: "ie", label: "Ireland" },
  { value: "il", label: "Israel" },
  { value: "it", label: "Italy" },
  { value: "jp", label: "Japan" },
  { value: "lv", label: "Latvia" },
  { value: "lt", label: "Lithuania" },
  { value: "my", label: "Malaysia" },
  { value: "mx", label: "mexico" },
  { value: "ma", label: "Morocco" },
  { value: "nl", label: "Netherlands" },
  { value: "nz", label: "New Zealand" },
  { value: "ng", label: "Nigeria" },
  { value: "no", label: "Norway" },
  { value: "ph", label: "Philippibes" },
  { value: "pl", label: "Poland" },
  { value: "pt", label: "Portugal" },
  { value: "ro", label: "Romania" },
  { value: "ru", label: "Russia" },
  { value: "sa", label: "Saudi Arabia" },
  { value: "rs", label: "Serbia" },
  { value: "sg", label: "Singapore" },
  { value: "sk", label: "Slovakia" },
  { value: "si", label: "Slovenia" },
  { value: "za", label: "South Africa" },
  { value: "kr", label: "South Korea" },
  { value: "se", label: "Sweden" },
  { value: "ch", label: "Switzerland" },
  { value: "tw", label: "Taiwan" },
  { value: "th", label: "Thailand" },
  { value: "tr", label: "Turkey" },
  { value: "ae", label: "UAE" },
  { value: "ua", label: "Ukraine" },
  { value: "gb", label: "United Kingdom" },
  { value: "us", label: "United States" },
  { value: "ve", label: "Venuzuela" },
]
